/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
	// Deletes ALL existing entries
	await knex("businesses").del();
	await knex("businesses").insert([
		{
			bizname: "Home Electric",
			bizcategory: "Electrician",
			bizimg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRy0TNQqjrk9uFoWoN0rOjrIn7GAuM1ic_yJA&usqp=CAU",
			bizdescription: "Description for business One",
			bizlocation: "123 Main St, Toronto, ON",
			user_id: 1,
		},
		{
			bizname: "Plumbing Plus",
			bizcategory: "Plumbing",
			bizimg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSL9O-Ut7sSq8Yv23zdTyRQ4MsJSe9MtUXWNw&usqp=CAU",
			bizdescription: "Description for business Two",
			bizlocation: "456 Elm St, Vancouver, BC",
			user_id: 2,
		},
		{
			bizname: "Beautify",
			bizcategory: "Cosmetology",
			bizimg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQK5UABvPNg4VzfRwd8Eq-1OvmN_3Jk17_Jaw&usqp=CAU",
			bizdescription: "Description for business Three",
			bizlocation: "789 Oak St, Montreal, QC",
			user_id: 3,
		},
		{
			bizname: "Spotless",
			bizcategory: "Cleaning",
			bizimg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRA0DExUPU93yo9J4HoPdekrvuOSLNUFPgttA&usqp=CAU",
			bizdescription: "Description for business Four",
			bizlocation: "159 Pine St, Calgary, AB",
			user_id: 4,
		},
		{
			bizname: "Green Thumb",
			bizcategory: "Landscaping",
			bizimg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-RSzpaLkRI9ArAwKyWOLZuJ_ipUDnHwPXKw&usqp=CAU",
			bizdescription: "Description for business Five",
			bizlocation: "753 Maple St, Halifax, NS",
			user_id: 5,
		},
		{
			bizname: "Shear Bliss",
			bizcategory: "Cosmetology",
			bizimg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRY8X-0m_C7kUC6Z9en59MkE6Yw5DuI68qvFw&usqp=CAU",
			bizdescription: "Description for business Seven",
			bizlocation: "357 Birch St, Ottawa, ON",
			user_id: 7,
		},
		{
			bizname: "Water Works",
			bizcategory: "Plumbing",
			bizimg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqGycDnR-4deefnbdNmKGsPmQWa-bIYEf4iQ&usqp=CAU",
			bizdescription: "Description for business Eight",
			bizlocation: "123 Maple Ave, Vancouver, BC",
			user_id: 8,
		},
		{
			bizname: "I'd Rather Be Cleaning",
			bizcategory: "Cleaning",
			bizimg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkZJbdQIEuTcNiAgDgy4mcfo-nyCwP82J7DQ&usqp=CAU",
			bizdescription: "Description for business Ten",
			bizlocation: "789 Oak St, Vancouver, BC",
			user_id: 10,
		},
		{
			bizname: "Electric Avenue",
			bizcategory: "Electrician",
			bizimg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEUGeUQa_W8cVEqj4fvmbaFy0iYhrmTLNewQ&usqp=CAU",
			bizdescription: "Description for Electric Avenue",
			bizlocation: "123 Main St, Toronto, ON",
			user_id: 11,
		},
		{
			bizname: "Pipe Dreams",
			bizcategory: "Plumbing",
			bizimg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6OS8IhK6Y9XVt5PE_33l4FXaQx4oLV8QkJA&usqp=CAU",
			bizdescription: "Description for Pipe Dreams",
			bizlocation: "456 Elm St, Vancouver, BC",
			user_id: 12,
		},
		{
			bizname: "Beauty and the Brush",
			bizcategory: "Cosmetology",
			bizimg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRNbgYAO4yxrEVAQGSTojRwNyEVyOl3oF8LxQ&usqp=CAU",
			bizdescription: "Description for Beauty and the Brush",
			bizlocation: "789 Oak St, Montreal, QC",
			user_id: 13,
		},
		{
			bizname: "Clean Sweep",
			bizcategory: "Cleaning",
			bizimg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7ULeOUaQDQA3O1IguDOo0W6lSvVgHEGPwfg&usqp=CAU",
			bizdescription: "Description for Clean Sweep",
			bizlocation: "159 Pine St, Calgary, AB",
			user_id: 14,
		},
		{
			bizname: "Grasshopper",
			bizcategory: "Landscaping",
			bizimg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvXCuKx9f6KSMf-BvEOa1uBXjQhJ1yaUIl4w&usqp=CAU",
			bizdescription: "Description for Green Thumb Landscaping",
			bizlocation: "753 Maple St, Halifax, NS",
			user_id: 15,
		},
		{
			bizname: "Lawn Ranger",
			bizcategory: "Landscaping",
			bizimg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSATtCFR0pUeMjh02BUt3mH-3dzuJMTh_09CQ&usqp=CAU",
			bizdescription: "Description for Chef's Table",
			bizlocation: "951 Cedar St, Winnipeg, MB",
			user_id: 16,
		},
		{
			bizname: "Wood Works",
			bizcategory: "Landscaping",
			bizimg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRX-wf1hvqrRq4Z-2T1QXWMV0_hW1qXy7PPw&usqp=CAU",
			bizdescription: "Description for Wood Works",
			bizlocation: "357 Birch St, Ottawa, ON",
			user_id: 17,
		},
		{
			bizname: "Greener Pastures",
			bizcategory: "Landscaping",
			bizimg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThtq-1tRfUI5GsR9esGLdrrTg37eN8WnWdMA&usqp=CAU",
			bizdescription: "Description for Greener Pastures",
			bizlocation: "456 Pine Dr, Vancouver, BC",
			user_id: 18,
		},
		{
			bizname: "Edward Scissorhands",
			bizcategory: "Cosmetology",
			bizimg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpJH3Crsv8ERMZFTjMI6MYTU9YSsyqXEnMgw&usqp=CAU",
			bizdescription: "Description for Edward Scissorhands",
			bizlocation: "321 Cedar Ln, Vancouver, BC",
			user_id: 19,
		},
		{
			bizname: "Evergreen",
			bizcategory: "Landscaping",
			bizimg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStyu74pLlvMG1CctC4Ao-3tePU-FAcsyNaBg&usqp=CAU",
			bizdescription: "Description for Evergreen",
			bizlocation: "987 Birch Pl, Vancouver, BC",
			user_id: 20,
		},
		{
			bizname: "The Handyman",
			bizcategory: "Plumbing",
			bizimg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1m3t4TqOfUj1_GYYH8VVZbr6ttaueMg84DA&usqp=CAU",
			bizdescription: "Description for The Handyman",
			bizlocation: "1234 Maple St, Toronto, ON",
			user_id: 11,
		},
		{
			bizname: "Mother Earth",
			bizcategory: "Landscaping",
			bizimg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTySXxZwoJt5RIFUH48IRPBN6nXuNkYeAPPxQ&usqp=CAU",
			bizdescription: "Description for Mother Earth",
			bizlocation: "5678 Elm St, Vancouver, BC",
			user_id: 12,
		},
		{
			bizname: "Deep Clean",
			bizcategory: "Cleaning",
			bizimg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR27ed3ZI4EzEfllkWrdCIborHHCMLSx_CtGg&usqp=CAU",
			bizdescription: "Description for The Carpenters",
			bizlocation: "9101 Oak St, Montreal, QC",
			user_id: 13,
		},
		{
			bizname: "Sanitation Station",
			bizcategory: "Cleaning",
			bizimg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSC36MoH8Rwtff6RYLolfrtP62eLrIWVi7x5g&usqp=CAU",
			bizdescription: "Description for The Florist",
			bizlocation: "1234 Rose St, Toronto, ON",
			user_id: 14,
		},
		{
			bizname: "Real Funny Ohms",
			bizcategory: "Electrician",
			bizimg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRESla9KAlSWseLNIeS3ZfPPLWsbZLTRhbVBA&usqp=CAU",
			bizdescription: "Description for The Baker",
			bizlocation: "5678 Bread St, Vancouver, BC",
			user_id: 15,
		},
		{
			bizname: "Sunny Side Up",
			bizcategory: "Landcaping",
			bizimg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8KH9YCJnTcGkg4Xqo1MwRkmcLWygaK_u6ow&usqp=CAU",
			bizdescription: "Description for Sunny Side Up",
			bizlocation: "123 Main St, Toronto, ON",
			user_id: 16,
		},
		{
			bizname: "Let The Sparks Fly",
			bizcategory: "Electrician",
			bizimg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTisdasauAivzhGUTzWfHo98s3OnE1prGcaIQ&usqp=CAU",
			bizdescription: "Description for Let The Sparks Fly",
			bizlocation: "456 Elm St, Vancouver, BC",
			user_id: 17,
		},
		{
			bizname: "High Voltage",
			bizcategory: "Electrician",
			bizimg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9cuo9NuTlVvh4FRDWhPUQ8DfIbEJ4N3Z5DQ&usqp=CAU",
			bizdescription: "Description for High Voltage",
			bizlocation: "789 Oak St, Montreal, QC",
			user_id: 18,
		},
		{
			bizname: "The Yellow Brick Road",
			bizcategory: "Plumbing",
			bizimg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZFDY6ROjxQMnkdiFJf6ciPpRKRyS3tLr14w&usqp=CAU",
			bizdescription: "Description for The Yellow Brick Road",
			bizlocation: "159 Pine St, Calgary, AB",
			user_id: 19,
		},
		{
			bizname: "The Golden Clipper",
			bizcategory: "Cosmetology",
			bizimg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmElIcdPm5_3ghxLQjyR69HZjT3okGJKigFw&usqp=CAU",
			bizdescription: "Description for The Golden Clipper",
			bizlocation: "753 Maple St, Halifax, NS",
			user_id: 20,
		},
		{
			bizname: "Heat Pumps R Us",
			bizcategory: "Electrician",
			bizimg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQV0JUj3gukPm-XIzW--k7g046U8P3I62LJjg&usqp=CAU",
			bizdescription: "Description for Heat Pumps R Us",
			bizlocation: "654 Spruce Ct, Vancouver, BC",
			user_id: 1,
		},
		{
			bizname: "Bright Spark",
			bizcategory: "Electrician",
			bizimg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpvC8LSZwyPttxJUI6FL42b2kqj5VujTnS5w&usqp=CAU",
			bizdescription: "Description for Bright Spark Electricians",
			bizlocation: "432 Willow Rd, Vancouver, BC",
			user_id: 2,
		},
		{
			bizname: "Pipe Dreams Plumbing",
			bizcategory: "Plumbing",
			bizimg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6T6v2nHiZRM_4KpqROycRgaAICbp88IA50Q&usqp=CAU",
			bizdescription: "Description for Pipe Dreams Plumbing",
			bizlocation: "876 Aspen Cr, Vancouver, BC",
			user_id: 3,
		},
		{
			bizname: "Flow Masters Plumbing",
			bizcategory: "Plumbing",
			bizimg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJhw4OJr_iEPhRsYuN5FZyWIsU6Y99kxCgjg&usqp=CAU",
			bizdescription: "Description for Flow Masters Plumbing",
			bizlocation: "543 Cherry St, Vancouver, BC",
			user_id: 4,
		},
		{
			bizname: "The Plumb Choice",
			bizcategory: "Plumbing",
			bizimg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQN3OKCqdaaZaJ7dMGNnMwyCo29tSZf2piUQ&usqp=CAU",
			bizdescription: "Description for The Plumb Choice",
			bizlocation: "765 Walnut Ave, Vancouver, BC",
			user_id: 5,
		},
		{
			bizname: "Polished Perfection",
			bizcategory: "Cosmetology",
			bizimg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvmhMgEyMPnVvo-vXuchtX1FABduQKT50Qmg&usqp=CAU",
			bizdescription: "Description for Polished Perfection",
			bizlocation: "234 Elm St, Vancouver, BC",
			user_id: 6,
		},
		{
			bizname: "Nailed It! Nail Salon",
			bizcategory: "Cosmetology",
			bizimg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRe4cU_tvNZDTxtBqpN5QSGRfAmhyWzObYIlw&usqp=CAU",
			bizdescription: "Description for Nailed It! Nail Salon",
			bizlocation: "891 Maple Dr, Vancouver, BC",
			user_id: 7,
		},
		{
			bizname: "Pristine Cleaners",
			bizcategory: "Cleaning",
			bizimg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnMO2DMZu86D4KEInW0RrX_RYZt18TUJZ5Tw&usqp=CAU",
			bizdescription: "Description for Pristine Cleaners",
			bizlocation: "567 Oak Ln, Vancouver, BC",
			user_id: 8,
		},
		{
			bizname: "Sparkle & Shine",
			bizcategory: "Cleaning",
			bizimg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS36_FXLCRSCeJw3gc0KhX04WXeByYSg0Z4HA&usqp=CAU",
			bizdescription: "Description for Sparkle & Shine Cleaning Co.",
			bizlocation: "345 Pine Pl, Vancouver, BC",
			user_id: 9,
		},
	]);
};
