/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
	// Deletes ALL existing entries
	await knex("comments").del();
	await knex("comments").insert([
		{ comment: "Did a great job 🤩", user_id: 8, business_id: 1 },
		{ comment: "Awesome service 😊", user_id: 1, business_id: 2 },
		{ comment: "🏆🏆🏆", user_id: 11, business_id: 3 },
		{ comment: "Did a great job 🤩", user_id: 11, business_id: 4 },
		{ comment: "💪🏽💪🏽💪🏽", user_id: 2, business_id: 5 },
		{ comment: "Awesome service 😊", user_id: 5, business_id: 6 },
		{ comment: "❤️❤️❤️", user_id: 4, business_id: 7 },
		{ comment: "🏆🏆🏆", user_id: 7, business_id: 8 },
		{ comment: "Highly recommended!!! ✅", user_id: 7, business_id: 9 },
		{ comment: "Did a great job 🤩", user_id: 1, business_id: 10 },
		{ comment: "Highly recommended!!! ✅", user_id: 10, business_id: 11 },
		{ comment: "❤️❤️❤️", user_id: 13, business_id: 12 },
		{ comment: "Awesome service 😊", user_id: 1, business_id: 13 },
		{ comment: "Top notch job! ⭐⭐", user_id: 1, business_id: 14 },
		{ comment: "💪🏽💪🏽💪🏽", user_id: 15, business_id: 15 },
		{ comment: "Highly recommended!!! ✅", user_id: 3, business_id: 16 },
		{ comment: "Did a great job 🤩", user_id: 9, business_id: 17 },
		{ comment: "Top notch job! ⭐⭐", user_id: 8, business_id: 18 },
		{ comment: "Did a great job 🤩", user_id: 17, business_id: 19 },
		{ comment: "❤️❤️❤️", user_id: 4, business_id: 20 },
		{ comment: "Awesome service 😊", user_id: 16, business_id: 21 },
		{ comment: "🏆🏆🏆", user_id: 14, business_id: 22 },
		{ comment: "Top notch job! ⭐⭐", user_id: 17, business_id: 23 },
		{ comment: "Did a great job 🤩", user_id: 9, business_id: 24 },
		{ comment: "Highly recommended!!! ✅", user_id: 5, business_id: 25 },
		{ comment: "Did a great job 🤩", user_id: 12, business_id: 1 },
		{ comment: "Top notch job! ⭐⭐", user_id: 13, business_id: 2 },
		{ comment: "❤️❤️❤️", user_id: 15, business_id: 3 },
		{ comment: "Awesome service 😊", user_id: 12, business_id: 4 },
		{ comment: "Top notch job! ⭐⭐", user_id: 6, business_id: 5 },
		{ comment: "❤️❤️❤️", user_id: 2, business_id: 6 },
		{ comment: "Did a great job 🤩", user_id: 4, business_id: 7 },
		{ comment: "Highly recommended!!! ✅", user_id: 5, business_id: 8 },
		{ comment: "🏆🏆🏆", user_id: 6, business_id: 9 },
		{ comment: "Top notch job! ⭐⭐", user_id: 8, business_id: 10 },
		{ comment: "❤️❤️❤️", user_id: 3, business_id: 11 },
		{ comment: "Awesome service 😊", user_id: 5, business_id: 12 },
		{ comment: "Highly recommended!!! ✅", user_id: 6, business_id: 13 },
		{ comment: "💪🏽💪🏽💪🏽", user_id: 7, business_id: 14 },
		{ comment: "Top notch job! ⭐⭐", user_id: 2, business_id: 15 },
		{ comment: "Did a great job 🤩", user_id: 2, business_id: 16 },
		{ comment: "❤️❤️❤️", user_id: 18, business_id: 17 },
		{ comment: "🏆🏆🏆", user_id: 19, business_id: 18 },
		{ comment: "Top notch job! ⭐⭐", user_id: 5, business_id: 19 },
		{ comment: "💪🏽💪🏽💪🏽", user_id: 6, business_id: 20 },
		{ comment: "Top notch job! ⭐⭐", user_id: 7, business_id: 21 },
		{ comment: "Awesome service 😊", user_id: 8, business_id: 22 },
		{ comment: "❤️❤️❤️", user_id: 9, business_id: 23 },
		{ comment: "Did a great job 🤩", user_id: 11, business_id: 24 },
		{ comment: "Highly recommended!!! ✅", user_id: 15, business_id: 25 },
		{ comment: "🏆🏆🏆", user_id: 16, business_id: 1 },
		{ comment: "Top notch job! ⭐⭐", user_id: 15, business_id: 2 },
		{ comment: "Did a great job 🤩", user_id: 14, business_id: 3 },
		{ comment: "❤️❤️❤️", user_id: 18, business_id: 4 },
		{ comment: "🏆🏆🏆", user_id: 14, business_id: 5 },
		{ comment: "Top notch job! ⭐⭐", user_id: 15, business_id: 6 },
		{ comment: "Awesome service 😊", user_id: 12, business_id: 7 },
		{ comment: "Top notch job! ⭐⭐", user_id: 11, business_id: 8 },
		{ comment: "💪🏽💪🏽💪🏽", user_id: 14, business_id: 9 },
		{ comment: "Did a great job 🤩", user_id: 4, business_id: 10 },
		{ comment: "Highly recommended!!! ✅", user_id: 5, business_id: 11 },
		{ comment: "🏆🏆🏆", user_id: 6, business_id: 12 },
		{ comment: "Highly recommended!!! ✅", user_id: 7, business_id: 13 },
		{ comment: "💪🏽💪🏽💪🏽", user_id: 8, business_id: 14 },
		{ comment: "Awesome service 😊", user_id: 9, business_id: 15 },
		{ comment: "Top notch job! ⭐⭐", user_id: 11, business_id: 16 },
		{ comment: "🏆🏆🏆", user_id: 12, business_id: 17 },
		{ comment: "Top notch job! ⭐⭐", user_id: 16, business_id: 18 },
		{ comment: "Did a great job 🤩", user_id: 15, business_id: 19 },
		{ comment: "❤️❤️❤️", user_id: 4, business_id: 20 },
		{ comment: "🏆🏆🏆", user_id: 5, business_id: 21 },
		{ comment: "Did a great job 🤩", user_id: 4, business_id: 22 },
		{ comment: "Highly recommended!!! ✅", user_id: 6, business_id: 23 },
		{ comment: "Awesome service 😊", user_id: 7, business_id: 24 },
		{ comment: "❤️❤️❤️", user_id: 3, business_id: 8 },
	]);
};
